apiVersion: v1
kind: Service
metadata:
  namespace: staging
  name: v4-mm-admin-staging-service
spec:
  type: NodePort
  selector:
    app: v4-mm-admin-staging
  ports:
    - port: 80
      nodePort: 30023